name: CI Build

on:
  push:
  pull_request:
  workflow_call:
    inputs:
      submodule:
        required: true
        type: string

jobs:   
  build:
    runs-on: ubuntu-20.04
    container:
      image: miyoocfw/toolchain:latest
    steps:
    - uses: actions/checkout@v2
    
    - if: inputs.submodule
      run: git submodule update --init --depth 1 -- ${{ inputs.submodule }}
    
    - name: Generate cache key
      if: inputs.submodule
      id: cache-key
      run: |
        cd ${{ inputs.submodule }}
        echo "::set-output name=key::${{ inputs.submodule }}-$(git rev-parse --short HEAD)"
      
    - uses: actions/cache@v3
      if: inputs.submodule
      with:
        path: ${{ inputs.submodule || '.' }}/dist/*
        key: ${{ steps.cache-key.outputs.key }}
      id: cache
      
    # ARCH=arm and CROSS_COMPILE=arm-buildroot-linux-musleabi- env props are set in the docker image
    # todo: build with 1-bit sdcard for new bittboy v1
    - name: build for Bittboy v2-3
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cd ${{ inputs.submodule || '.' }}
        make miyoo_defconfig
        make
        
        # put everything in the same folder so that we can grab it all as a single artifact
    - name: gather Bittboy v2-3 files
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cd ${{ inputs.submodule || '.' }}
        mkdir -p dist/bittboy-2-3
        mv arch/arm/boot/dts/suniv-f1c500s-miyoo.dtb dist/bittboy-2-3/
        mv arch/arm/boot/zImage dist/bittboy-2-3/
        mv drivers/video/fbdev/core/*.ko dist/bittboy-2-3/
        mv drivers/video/fbdev/r61520fb.ko dist/bittboy-2-3/
 

    - name: build for PocketGo, V90, & Q90
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cd ${{ inputs.submodule || '.' }}
        make miyoo_pocketgo_defconfig
        make
        
        # put everything in the same folder so that we can grab it all as a single artifact
    - name: gather PocketGo, V90, & Q90 files
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cd ${{ inputs.submodule || '.' }}
        mkdir -p dist/pocketgo-v90-q90
        mv arch/arm/boot/dts/suniv-f1c500s-miyoo.dtb dist/pocketgo-v90-q90/
        mv arch/arm/boot/zImage dist/pocketgo-v90-q90/
        mv drivers/video/fbdev/core/*.ko dist/pocketgo-v90-q90/
        mv drivers/video/fbdev/r61520fb.ko dist/pocketgo-v90-q90/
 
    - name: build for M3
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cd ${{ inputs.submodule || '.' }}
        make miyoo_m3_defconfig
        make
        
    - name: gather M3 files
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cd ${{ inputs.submodule || '.' }}
        mkdir -p dist/m3
        mv arch/arm/boot/dts/suniv-f1c500s-miyoo.dtb dist/m3/
        mv arch/arm/boot/zImage dist/m3/
        mv drivers/video/fbdev/core/*.ko dist/m3/
        mv drivers/video/fbdev/r61520fb.ko dist/m3/

    - name: build for Q8
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cd ${{ inputs.submodule || '.' }}
        make miyoo_q8_defconfig
        make
        
        # put everything in the same folder so that we can grab it all as a single artifact
    - name: gather Q8 files
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cd ${{ inputs.submodule || '.' }}
        mkdir -p dist/q8
        mv arch/arm/boot/dts/suniv-f1c500s-miyoo.dtb dist/q8/
        mv arch/arm/boot/zImage dist/q8/
        mv drivers/video/fbdev/core/*.ko dist/q8/
        mv drivers/video/fbdev/r61520fb.ko dist/q8/

    - run: find ${{ inputs.submodule || '.' }}/dist
    
    - uses: actions/upload-artifact@v2
      with:
        name: kernel
        path: ${{ inputs.submodule || '.' }}/dist/*
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`
